apiVersion: v1
kind: Service
metadata:
  name: {{ include "server-monitoring.fullname" . }}-node-exporter
  labels:
    {{- include "server-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
spec:
  type: ClusterIP
  selector:
    {{- include "server-monitoring.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
  ports:
    - name: metrics
      port: {{ .Values.nodeExporter.service.port }}
      targetPort: 9100
      protocol: TCP
