apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "server-monitoring.fullname" . }}-node-exporter
  labels:
    {{- include "server-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-exporter
spec:
  selector:
    matchLabels:
      {{- include "server-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: node-exporter
  template:
    metadata:
      labels:
        {{- include "server-monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: node-exporter
    spec:
      hostNetwork: true
      hostPID: true
      containers:
        - name: node-exporter
          image: "{{ .Values.nodeExporter.image.repository }}:{{ .Values.nodeExporter.image.tag }}"
          imagePullPolicy: {{ .Values.nodeExporter.image.pullPolicy }}
          args:
            - --path.rootfs=/host
          ports:
            - name: metrics
              containerPort: 9100
              hostPort: 9100
              protocol: TCP
          resources:
            {{- toYaml .Values.nodeExporter.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: root
              mountPath: /host
              readOnly: true
      volumes:
        - name: root
          hostPath:
            path: /
