apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server-monitoring.fullname" . }}-prometheus
  labels:
    {{- include "server-monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "server-monitoring.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: prometheus
  template:
    metadata:
      labels:
        {{- include "server-monitoring.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prometheus
    spec:
      containers:
        - name: prometheus
          image: "{{ .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}"
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.prometheus.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: {{ include "server-monitoring.fullname" . }}-prometheus
        - name: data
          {{- if .Values.prometheus.storage.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "server-monitoring.fullname" . }}-prometheus
          {{- else }}
          emptyDir: {}
          {{- end }}
